export GOPATH=/Project/Go
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/sbin"
export PATH="$PATH:/usr/bin"

export GO111MODULE=on
export GOPROXY=http://goproxy.io

