version: '2.1'

networks:
  monitor-net:
    driver: bridge

networks:
  monitor-net:
    name: monitor-net

services:
  grafana:
    image: grafana/grafana:6.3.6
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  redis1:
    image: publicisworldwide/redis-cluster
    restart: always
    container_name: redis1
    volumes:
     - ./redis/8001/data:/data
    environment:
     - REDIS_PORT=8001
    ports:
      - '8001:8001'       #服务端口
      - '18001:18001'   #集群端口
    networks:
        - monitor-net

  redis2:
    image: publicisworldwide/redis-cluster
    restart: always
    container_name: redis2
    volumes:
     - ./redis/8002/data:/data
    environment:
     - REDIS_PORT=8002
    ports:
      - '8002:8002'
      - '18002:18002'
    networks:
        - monitor-net


  redis3:
    image: publicisworldwide/redis-cluster
    restart: always
    container_name: redis3
    volumes:
     - ./redis/8003/data:/data
    environment:
     - REDIS_PORT=8003
    ports:
      - '8003:8003'
      - '18003:18003'
    networks:
        - monitor-net

  redis-exporter:
    image: oliver006/redis_exporter:v0.15.0
    ports:
      - 9121:9121
    networks:
      - monitor-net
    command:
      - '--redis.addr=redis://redis1:8001'
