version: '2'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - front_default
    hostname: test1
    container_name: test1

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
    networks:
      - front_default
    hostname: test2
    container_name: test2

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - front_default
    hostname: test3
    container_name: test3

networks:
  front_default:
#  app:
#  app:
#    build: ./app/
#    ports:
#      - "3001:3001"
#    depends_on:
#      - prometheus
#      - grafana