global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: app
    scrape_interval: 1s
    scrape_timeout: 1s
    static_configs:
      - targets: ["app:3001"]